//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_IT6NSI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Instrument { get; set; }
        public string Piece { get; set; }
    }
}
